name: Deploy
on:
  push:
    branches: ['main', 'cursor/palmeirasapp-1aeb']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: zcloud-ws/zcloud-deploy-action@main
        with:
          env-token: ${{ secrets.QUAVE_ONE_PROD_TOKEN }}
          env: "filipenevola-palmeirasapp-production"
