name: Deploy
on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Deploy
        uses: quaveone/quaveone-deploy-action@main
        with:
          env-token: ${{ secrets.QUAVEONE_ENV_TOKEN }}
          env: "filipenevola-filipenevola-production"
